os: linux
dist: trusty
sudo: required
language: c
compiler: avr-gcc
branches:
  except:
    - /^.*-automated-build$/
env:
  global:
  - secure: vBTSL34BDPxDilKUuTXqU4CJ26Pv5hogD2nghatkxSQkI1/jbdnLj/DQdPUrMJFDIY6TK3AltsBx72MaMsLQ1JO/Ou24IeHINHXzUC1FlS9yQa48cpxnhX5kzXNyGs3oa0qaFbvnr7RgYRWtmD52n4bIZuSuW+xpBv05x2OCizdT2ZonH33nATaHGFasxROm4qYZ241VfzcUv766V6RVHgL4x9V08warugs+RENVkfzxxwhk3NmkrISabze0gSVJLHBPHxroZC6EUcf/ocobcuDrCwFqtEt90i7pNIAFUE7gZsN2uE75LmpzAWin21G7lLPcPL2k4FJVd8an1HiP2WmscJU6U89fOfMb2viObnKcCzebozBCmKGtHEuXZo9FcReOx49AnQSpmESJGs+q2dL/FApkTjQiyT4J6O5dJpoww0/r57Wx0cmmqjETKBb5rSgXM51Etk3wO09mvcPHsEwrT7qH8r9XWdyCDoEn7FCLX3/LYnf/D4SmZ633YPl5gv3v9XEwxR5+04akjgnvWDSNIaDbWBdxHNb7l4pMc+WR1bwCyMyA7KXj0RrftEGOrm9ZRLe6BkbT4cycA+j77nbPOMcyZChliV9pPQos+4TOJoTzcK2L8yWVoY409aDNVuAjdP6Yum0R2maBGl/etLmIMpJC35C5/lZ+dUNjJAM=
  matrix:
  - TARGET=all-keyboards AUTOGEN=true
  - TARGET=test AUTOGEN=false
script:
- make $TARGET AUTOGEN=$AUTOGEN
addons:
  apt:
    packages:
    - avr-libc
    - gcc-avr
    - dfu-programmer
    - pandoc
    - gcc-arm-none-eabi
    - binutils-arm-none-eabi
    - libnewlib-arm-none-eabi
    - diffutils
after_success: 
  if [ "$AUTOGEN" == "true" ]; then
    bash util/travis_compiled_push.sh;
  fi
